Fix: Add/remove aria-expanded attribute along with drawer visibility
adaptlearning/adapt-contrib-drawer pull request #2
Opened 2023-07-03 08:24 UTC by cahirodoherty-learningpool

[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
Fixes #1 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* aria-expanded attribute added/removed according to drawer visibility

2023-07-03 08:58 UTC, eleanor-heath approved these changes

2023-07-03 09:03 UTC, ethan-lp approved these changes

2023-07-03 09:15 UTC, lemmyadams approved these changes

2023-07-17 14:44 UTC, oliverfoster requested changes
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded

`aria-expanded="false"` is also meaningful

2023-07-17 14:44 UTC, oliverfoster commented on js/DrawerView.js
> +    this.$el.removeClass('u-display-none').removeAttr('aria-hidden').attr('aria-expanded');
```suggestion
    this.$el.removeClass('u-display-none').removeAttr('aria-hidden').attr('aria-expanded', 'true');
```

2023-07-17 14:44 UTC, oliverfoster commented on js/DrawerView.js
> +        .removeAttr('aria-expanded');
```suggestion
        .attr('aria-hidden', 'true')
        .attr('aria-expanded', 'false');
```

2023-07-17 14:46 UTC, oliverfoster commented
Did you mean to update this extension? It's not in use at the moment.

2023-07-18 07:49 UTC, cahirodoherty-learningpool commented
> Did you mean to update this extension? It's not in use at the moment. This behaviour is in adapt-contrib-core.

I am an idiot 🤣

2023-08-07 11:00 UTC, closed without merging